/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

/**
 *
 * @author Andrea
 */
public class formularioUnidad extends javax.swing.JFrame {

    /**
     * Creates new form formularioUnidad
     */
    public formularioUnidad() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formularioUnidad = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        codigoUnidadOperativa = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        codigoSedeUnidad = new javax.swing.JTextField();
        fichaEmpleadoResponsable = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nombreUnidad = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        unidadAtras = new javax.swing.JButton();
        agUnidadOperativa = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        formularioUnidad.setBackground(new java.awt.Color(255, 255, 255));
        formularioUnidad.setPreferredSize(new java.awt.Dimension(1200, 660));
        formularioUnidad.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Ficha de responsable");
        formularioUnidad.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, -1, -1));

        codigoUnidadOperativa.setBackground(new java.awt.Color(255, 255, 255));
        codigoUnidadOperativa.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        codigoUnidadOperativa.setForeground(new java.awt.Color(51, 51, 51));
        codigoUnidadOperativa.setText("Codigo Unidad");
        codigoUnidadOperativa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoUnidadOperativaActionPerformed(evt);
            }
        });
        formularioUnidad.add(codigoUnidadOperativa, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 190, 40));

        jLabel1.setFont(new java.awt.Font("Bell MT", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Agregar una Unidad Operativa");
        formularioUnidad.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 530, 70));

        codigoSedeUnidad.setBackground(new java.awt.Color(255, 255, 255));
        codigoSedeUnidad.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        codigoSedeUnidad.setForeground(new java.awt.Color(51, 51, 51));
        codigoSedeUnidad.setText("Codigo Sede");
        formularioUnidad.add(codigoSedeUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 190, 40));

        fichaEmpleadoResponsable.setBackground(new java.awt.Color(255, 255, 255));
        fichaEmpleadoResponsable.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        fichaEmpleadoResponsable.setForeground(new java.awt.Color(51, 51, 51));
        fichaEmpleadoResponsable.setText("Ficha empleado responsable");
        fichaEmpleadoResponsable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fichaEmpleadoResponsableActionPerformed(evt);
            }
        });
        formularioUnidad.add(fichaEmpleadoResponsable, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 190, 40));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Codigo de Unidad");
        formularioUnidad.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Codigo Sede");
        formularioUnidad.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        nombreUnidad.setBackground(new java.awt.Color(255, 255, 255));
        nombreUnidad.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        nombreUnidad.setForeground(new java.awt.Color(51, 51, 51));
        nombreUnidad.setText("Nombre de Unidad Operativa");
        nombreUnidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreUnidadActionPerformed(evt);
            }
        });
        formularioUnidad.add(nombreUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 190, 40));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Nombre Unidad");
        formularioUnidad.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, -1, -1));

        unidadAtras.setBackground(new java.awt.Color(255, 255, 255));
        unidadAtras.setForeground(new java.awt.Color(255, 255, 255));
        unidadAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosInterface/back.png"))); // NOI18N
        unidadAtras.setBorder(null);
        unidadAtras.setBorderPainted(false);
        unidadAtras.setContentAreaFilled(false);
        unidadAtras.setFocusPainted(false);
        unidadAtras.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosInterface/back (2).png"))); // NOI18N
        unidadAtras.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosInterface/back (2).png"))); // NOI18N
        unidadAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unidadAtrasActionPerformed(evt);
            }
        });
        formularioUnidad.add(unidadAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 70));

        agUnidadOperativa.setBackground(new java.awt.Color(255, 255, 255));
        agUnidadOperativa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosInterface/add (1).png"))); // NOI18N
        agUnidadOperativa.setBorder(null);
        agUnidadOperativa.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosInterface/add (2).png"))); // NOI18N
        agUnidadOperativa.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosInterface/add (2).png"))); // NOI18N
        agUnidadOperativa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agUnidadOperativaActionPerformed(evt);
            }
        });
        formularioUnidad.add(agUnidadOperativa, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, 190, 90));

        jLabel9.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Agregar Unidad Operativa");
        formularioUnidad.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 370, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(formularioUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(formularioUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void codigoUnidadOperativaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoUnidadOperativaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoUnidadOperativaActionPerformed

    private void nombreUnidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreUnidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreUnidadActionPerformed

    private void fichaEmpleadoResponsableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fichaEmpleadoResponsableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fichaEmpleadoResponsableActionPerformed

    private void unidadAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unidadAtrasActionPerformed
        listaUnidadOperativa luo = new listaUnidadOperativa();
        luo.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_unidadAtrasActionPerformed

    private void agUnidadOperativaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agUnidadOperativaActionPerformed
        listaUnidadOperativa luo = new listaUnidadOperativa();
        luo.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_agUnidadOperativaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formularioUnidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formularioUnidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formularioUnidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formularioUnidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formularioUnidad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agUnidadOperativa;
    private javax.swing.JTextField codigoSedeUnidad;
    private javax.swing.JTextField codigoUnidadOperativa;
    private javax.swing.JTextField fichaEmpleadoResponsable;
    private javax.swing.JPanel formularioUnidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nombreUnidad;
    private javax.swing.JButton unidadAtras;
    // End of variables declaration//GEN-END:variables
}
