/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.EntityTransaction;
import javax.persistence.Persistence;

/**
 *
 * @author Andrea
 */
public class formularioMovilizacion extends javax.swing.JFrame {

    /**
     * Creates new form formularioMovilizacion
     */
    
    EntityManagerFactory emf = Persistence.createEntityManagerFactory("InventarioPU");
    EntityManager em = emf.createEntityManager();
    EntityTransaction datosTransaccion = em.getTransaction();
    
    public formularioMovilizacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formularioActivoNatural = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        movilizacionCodigoUnidadC = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        movilizacionCodigoUnidadR = new javax.swing.JTextField();
        movilizacionCodigoActivo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        movilizacionCodigoResponsableC = new javax.swing.JTextField();
        movilizacionCodigoResponsableR = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        movilizacionMotivo = new javax.swing.JTextField();
        movilizacionAtras = new javax.swing.JButton();
        agMovilizacion = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        fechaMovilizacion = new javax.swing.JTextField();
        seleccionTipoActivo = new javax.swing.JComboBox<>();
        seleccionTipoActivo1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        formularioActivoNatural.setBackground(new java.awt.Color(255, 255, 255));
        formularioActivoNatural.setPreferredSize(new java.awt.Dimension(1200, 660));
        formularioActivoNatural.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Codigo de Activo");
        formularioActivoNatural.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, -1, -1));

        movilizacionCodigoUnidadC.setBackground(new java.awt.Color(255, 255, 255));
        movilizacionCodigoUnidadC.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        movilizacionCodigoUnidadC.setForeground(new java.awt.Color(51, 51, 51));
        movilizacionCodigoUnidadC.setText("Codigo Unidad Operativa Cedente");
        movilizacionCodigoUnidadC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movilizacionCodigoUnidadCActionPerformed(evt);
            }
        });
        formularioActivoNatural.add(movilizacionCodigoUnidadC, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 300, 40));

        jLabel1.setFont(new java.awt.Font("Bell MT", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Agregar Movilizacion");
        formularioActivoNatural.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 540, 70));

        movilizacionCodigoUnidadR.setBackground(new java.awt.Color(255, 255, 255));
        movilizacionCodigoUnidadR.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        movilizacionCodigoUnidadR.setForeground(new java.awt.Color(51, 51, 51));
        movilizacionCodigoUnidadR.setText("Codigo Unidad Operativa Receptora");
        formularioActivoNatural.add(movilizacionCodigoUnidadR, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 300, 40));

        movilizacionCodigoActivo.setBackground(new java.awt.Color(255, 255, 255));
        movilizacionCodigoActivo.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        movilizacionCodigoActivo.setForeground(new java.awt.Color(51, 51, 51));
        movilizacionCodigoActivo.setText("Codigo de Activo");
        formularioActivoNatural.add(movilizacionCodigoActivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 190, 40));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Codigo Responsable Receptor");
        formularioActivoNatural.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 300, 40));

        movilizacionCodigoResponsableC.setBackground(new java.awt.Color(255, 255, 255));
        movilizacionCodigoResponsableC.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        movilizacionCodigoResponsableC.setForeground(new java.awt.Color(51, 51, 51));
        movilizacionCodigoResponsableC.setText("Codigo Responsable Cedente");
        formularioActivoNatural.add(movilizacionCodigoResponsableC, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 300, 40));

        movilizacionCodigoResponsableR.setBackground(new java.awt.Color(255, 255, 255));
        movilizacionCodigoResponsableR.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        movilizacionCodigoResponsableR.setForeground(new java.awt.Color(51, 51, 51));
        movilizacionCodigoResponsableR.setText("Codigo Responsable Receptor");
        formularioActivoNatural.add(movilizacionCodigoResponsableR, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 300, 40));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Motivo");
        formularioActivoNatural.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, -1, -1));

        movilizacionMotivo.setBackground(new java.awt.Color(255, 255, 255));
        movilizacionMotivo.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        movilizacionMotivo.setForeground(new java.awt.Color(51, 51, 51));
        movilizacionMotivo.setText("Motivo");
        movilizacionMotivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movilizacionMotivoActionPerformed(evt);
            }
        });
        formularioActivoNatural.add(movilizacionMotivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 300, 40));

        movilizacionAtras.setBackground(new java.awt.Color(255, 255, 255));
        movilizacionAtras.setForeground(new java.awt.Color(255, 255, 255));
        movilizacionAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosInterface/back.png"))); // NOI18N
        movilizacionAtras.setBorder(null);
        movilizacionAtras.setBorderPainted(false);
        movilizacionAtras.setContentAreaFilled(false);
        movilizacionAtras.setFocusPainted(false);
        movilizacionAtras.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosInterface/back (2).png"))); // NOI18N
        movilizacionAtras.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosInterface/back (2).png"))); // NOI18N
        movilizacionAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movilizacionAtrasActionPerformed(evt);
            }
        });
        formularioActivoNatural.add(movilizacionAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 70));

        agMovilizacion.setBackground(new java.awt.Color(255, 255, 255));
        agMovilizacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosInterface/add (1).png"))); // NOI18N
        agMovilizacion.setBorder(null);
        agMovilizacion.setBorderPainted(false);
        agMovilizacion.setContentAreaFilled(false);
        agMovilizacion.setFocusPainted(false);
        agMovilizacion.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosInterface/add (2).png"))); // NOI18N
        agMovilizacion.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosInterface/add (2).png"))); // NOI18N
        agMovilizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agMovilizacionActionPerformed(evt);
            }
        });
        formularioActivoNatural.add(agMovilizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, 190, 90));

        jLabel9.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Agregar Movilizacion");
        formularioActivoNatural.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 440, -1, -1));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Codigo Unidad Operativa Cedente");
        formularioActivoNatural.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 280, 40));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Codigo Unidad Operativa Recpectora");
        formularioActivoNatural.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 300, 40));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Codigo Responsable Cedente");
        formularioActivoNatural.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 300, 40));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Fecha de Movilizacion");
        formularioActivoNatural.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, -1, -1));

        fechaMovilizacion.setBackground(new java.awt.Color(255, 255, 255));
        fechaMovilizacion.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        fechaMovilizacion.setForeground(new java.awt.Color(51, 51, 51));
        fechaMovilizacion.setText("Fecha de Movilizacion");
        fechaMovilizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaMovilizacionActionPerformed(evt);
            }
        });
        formularioActivoNatural.add(fechaMovilizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, 190, 40));

        seleccionTipoActivo.setBackground(new java.awt.Color(255, 255, 255));
        seleccionTipoActivo.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        seleccionTipoActivo.setForeground(new java.awt.Color(0, 0, 0));
        seleccionTipoActivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aprobación de Receptor", "SI", "NO" }));
        seleccionTipoActivo.setToolTipText("");
        seleccionTipoActivo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 1, true));
        seleccionTipoActivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionTipoActivoActionPerformed(evt);
            }
        });
        formularioActivoNatural.add(seleccionTipoActivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, 190, -1));

        seleccionTipoActivo1.setBackground(new java.awt.Color(255, 255, 255));
        seleccionTipoActivo1.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        seleccionTipoActivo1.setForeground(new java.awt.Color(0, 0, 0));
        seleccionTipoActivo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aprobación de Cedente", "SI", "NO" }));
        seleccionTipoActivo1.setToolTipText("");
        seleccionTipoActivo1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 1, true));
        seleccionTipoActivo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionTipoActivo1ActionPerformed(evt);
            }
        });
        formularioActivoNatural.add(seleccionTipoActivo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, 190, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(formularioActivoNatural, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(formularioActivoNatural, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void movilizacionCodigoUnidadCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movilizacionCodigoUnidadCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_movilizacionCodigoUnidadCActionPerformed

    private void movilizacionMotivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movilizacionMotivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_movilizacionMotivoActionPerformed

    private void movilizacionAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movilizacionAtrasActionPerformed
        listaMovilizacion lm = new listaMovilizacion();
        lm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_movilizacionAtrasActionPerformed

    private void agMovilizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agMovilizacionActionPerformed
        listaMovilizacion luo = new listaMovilizacion();
        em.getTransaction().begin();
        em.createNativeQuery("INSERT INTO movilizacion (id_unidadc, id_unidadr, id_responsableuc, id_responsableur, id_activo, f_movilizacion, aprobacionc, aprobacionr, motivo) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)")
                .setParameter(1, this.movilizacionCodigoUnidadC.getText())
                .setParameter(2, this.movilizacionCodigoUnidadR.getText())
                .setParameter(3, this.movilizacionCodigoResponsableC.getText())
                .setParameter(4, this.movilizacionCodigoResponsableR.getText())
                .setParameter(5, this.movilizacionCodigoActivo.getText())
                .setParameter(6, this.fechaMovilizacion.getText())
                .setParameter(7, this.seleccionTipoActivo1.getSelectedItem().toString())
                .setParameter(8, this.seleccionTipoActivo.getSelectedItem().toString())
                .setParameter(9, this.movilizacionMotivo.getText())
                .executeUpdate();
        em.flush();
        datosTransaccion.commit();
        em.close();
        luo.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_agMovilizacionActionPerformed

    private void fechaMovilizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaMovilizacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaMovilizacionActionPerformed

    private void seleccionTipoActivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionTipoActivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seleccionTipoActivoActionPerformed

    private void seleccionTipoActivo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionTipoActivo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seleccionTipoActivo1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formularioMovilizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formularioMovilizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formularioMovilizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formularioMovilizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formularioMovilizacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agMovilizacion;
    private javax.swing.JTextField fechaMovilizacion;
    private javax.swing.JPanel formularioActivoNatural;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton movilizacionAtras;
    private javax.swing.JTextField movilizacionCodigoActivo;
    private javax.swing.JTextField movilizacionCodigoResponsableC;
    private javax.swing.JTextField movilizacionCodigoResponsableR;
    private javax.swing.JTextField movilizacionCodigoUnidadC;
    private javax.swing.JTextField movilizacionCodigoUnidadR;
    private javax.swing.JTextField movilizacionMotivo;
    private javax.swing.JComboBox<String> seleccionTipoActivo;
    private javax.swing.JComboBox<String> seleccionTipoActivo1;
    // End of variables declaration//GEN-END:variables
}
