/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import static Interface.formularioActivo.id_activo_ingresado;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.EntityTransaction;
import javax.persistence.Persistence;

/**
 *
 * @author Andrea
 */
public class formularioActivoTangible extends javax.swing.JFrame {

    /**
     * Creates new form activoTangible
     */
    
    EntityManagerFactory emf = Persistence.createEntityManagerFactory("InventarioPU");
    EntityManager em = emf.createEntityManager();
    EntityTransaction datosTransaccion = em.getTransaction();
    
    public formularioActivoTangible() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        formularioActivoTangible = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nombreProveedor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        numOrden = new javax.swing.JTextField();
        numFactura = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        plazoGarantia = new javax.swing.JTextField();
        activoTangibleStatus = new javax.swing.JComboBox<>();
        activoTangibleCompomente = new javax.swing.JButton();
        agActivoTangible = new javax.swing.JButton();
        activoTangibleAtras = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        formularioActivoTangible.setBackground(new java.awt.Color(255, 255, 255));
        formularioActivoTangible.setPreferredSize(new java.awt.Dimension(1200, 660));
        formularioActivoTangible.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Numero de Factura");
        formularioActivoTangible.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, -1, -1));

        nombreProveedor.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        nombreProveedor.setForeground(new java.awt.Color(51, 51, 51));
        nombreProveedor.setText("Nombre de Proveedor");
        nombreProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreProveedorActionPerformed(evt);
            }
        });
        formularioActivoTangible.add(nombreProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 190, 40));

        jLabel1.setFont(new java.awt.Font("Bell MT", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Agregar un Activo Tangible");
        formularioActivoTangible.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 530, 70));

        numOrden.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        numOrden.setForeground(new java.awt.Color(51, 51, 51));
        numOrden.setText("Numero de orden");
        formularioActivoTangible.add(numOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 190, 40));

        numFactura.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        numFactura.setForeground(new java.awt.Color(51, 51, 51));
        numFactura.setText("Numero de Factura");
        formularioActivoTangible.add(numFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 190, 40));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Proveedor");
        formularioActivoTangible.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 190, 30));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Numero de Orden");
        formularioActivoTangible.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, 20));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Plazo de Garantia");
        formularioActivoTangible.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 160, -1));

        plazoGarantia.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        plazoGarantia.setForeground(new java.awt.Color(51, 51, 51));
        plazoGarantia.setText("Plazo de Garantia");
        plazoGarantia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plazoGarantiaActionPerformed(evt);
            }
        });
        formularioActivoTangible.add(plazoGarantia, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 190, 40));

        activoTangibleStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo Tangible Status", "En proceso de registro", "Activo", "Dañado", "Obsoleto", "En reparación", "Desincorporado" }));
        activoTangibleStatus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        formularioActivoTangible.add(activoTangibleStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 190, -1));

        activoTangibleCompomente.setBackground(new java.awt.Color(255, 255, 255));
        activoTangibleCompomente.setText("Componente");
        activoTangibleCompomente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        activoTangibleCompomente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activoTangibleCompomenteActionPerformed(evt);
            }
        });
        formularioActivoTangible.add(activoTangibleCompomente, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, 190, 30));

        agActivoTangible.setBackground(new java.awt.Color(255, 255, 255));
        agActivoTangible.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosInterface/add (1).png"))); // NOI18N
        agActivoTangible.setBorder(null);
        agActivoTangible.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosInterface/add (2).png"))); // NOI18N
        agActivoTangible.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosInterface/add (2).png"))); // NOI18N
        agActivoTangible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agActivoTangibleActionPerformed(evt);
            }
        });
        formularioActivoTangible.add(agActivoTangible, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 360, 190, 90));

        activoTangibleAtras.setBackground(new java.awt.Color(255, 255, 255));
        activoTangibleAtras.setForeground(new java.awt.Color(255, 255, 255));
        activoTangibleAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosInterface/back.png"))); // NOI18N
        activoTangibleAtras.setBorder(null);
        activoTangibleAtras.setBorderPainted(false);
        activoTangibleAtras.setContentAreaFilled(false);
        activoTangibleAtras.setFocusPainted(false);
        activoTangibleAtras.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosInterface/back (2).png"))); // NOI18N
        activoTangibleAtras.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosInterface/back (2).png"))); // NOI18N
        activoTangibleAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activoTangibleAtrasActionPerformed(evt);
            }
        });
        formularioActivoTangible.add(activoTangibleAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 70));

        jLabel4.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel4.setText("Agregar Activo");
        formularioActivoTangible.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 450, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(formularioActivoTangible, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(formularioActivoTangible, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreProveedorActionPerformed

    private void agActivoTangibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agActivoTangibleActionPerformed
        listaActivo la = new listaActivo();
        em.getTransaction().begin();
        em.createNativeQuery("INSERT INTO activo_tangible (id_activo, proveedor, num_orden, num_factura, plazo_garantia, status) VALUES (?, ?, ?, ?, ?, ?)")
                .setParameter(1, id_activo_ingresado)
                .setParameter(2, this.nombreProveedor.getText())
                .setParameter(3, this.numOrden.getText())
                .setParameter(4, this.numFactura.getText())
                .setParameter(5, this.plazoGarantia.getText())
                .setParameter(6, this.activoTangibleStatus.getSelectedItem().toString())
                .executeUpdate();
        em.flush();
        datosTransaccion.commit();
        em.close();
        la.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_agActivoTangibleActionPerformed

    private void activoTangibleCompomenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activoTangibleCompomenteActionPerformed
        formularioActivoComponente fac = new formularioActivoComponente();
        fac.setVisible(true);
        this.setVisible(false);
        
        
    }//GEN-LAST:event_activoTangibleCompomenteActionPerformed

    private void activoTangibleAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activoTangibleAtrasActionPerformed
        formularioActivo la = new formularioActivo();
        la.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_activoTangibleAtrasActionPerformed

    private void plazoGarantiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plazoGarantiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_plazoGarantiaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formularioActivoTangible.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formularioActivoTangible.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formularioActivoTangible.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formularioActivoTangible.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formularioActivoTangible().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton activoTangibleAtras;
    private javax.swing.JButton activoTangibleCompomente;
    private javax.swing.JComboBox<String> activoTangibleStatus;
    private javax.swing.JButton agActivoTangible;
    private javax.swing.JPanel formularioActivoTangible;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField nombreProveedor;
    private javax.swing.JTextField numFactura;
    private javax.swing.JTextField numOrden;
    private javax.swing.JTextField plazoGarantia;
    // End of variables declaration//GEN-END:variables
}
