/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import static Interface.formularioActivo.id_activo_ingresado;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.EntityTransaction;
import javax.persistence.Persistence;

/**
 *
 * @author Andrea
 */
public class formularioActivoComponente extends javax.swing.JFrame {

    /**
     * Creates new form activoComponente
     */
    
    EntityManagerFactory emf = Persistence.createEntityManagerFactory("InventarioPU");
    EntityManager em = emf.createEntityManager();
    EntityTransaction datosTransaccion = em.getTransaction();
    
    public formularioActivoComponente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuActivo = new javax.swing.JPanel();
        codigoActivo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        activoAtras = new javax.swing.JButton();
        agComponente = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuActivo.setBackground(new java.awt.Color(255, 255, 255));
        menuActivo.setPreferredSize(new java.awt.Dimension(1200, 660));
        menuActivo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        codigoActivo.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        codigoActivo.setForeground(new java.awt.Color(51, 51, 51));
        codigoActivo.setText("nombre Componente");
        codigoActivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoActivoActionPerformed(evt);
            }
        });
        menuActivo.add(codigoActivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 190, 40));

        jLabel1.setFont(new java.awt.Font("Bell MT", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Agregar un Componente");
        menuActivo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 520, 70));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Nombre Componente");
        menuActivo.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 190, -1));

        activoAtras.setBackground(new java.awt.Color(255, 255, 255));
        activoAtras.setForeground(new java.awt.Color(255, 255, 255));
        activoAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosInterface/back.png"))); // NOI18N
        activoAtras.setBorder(null);
        activoAtras.setBorderPainted(false);
        activoAtras.setContentAreaFilled(false);
        activoAtras.setFocusPainted(false);
        activoAtras.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosInterface/back (2).png"))); // NOI18N
        activoAtras.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosInterface/back (2).png"))); // NOI18N
        activoAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activoAtrasActionPerformed(evt);
            }
        });
        menuActivo.add(activoAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 70));

        agComponente.setBackground(new java.awt.Color(255, 255, 255));
        agComponente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosInterface/add (1).png"))); // NOI18N
        agComponente.setBorder(null);
        agComponente.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosInterface/add (2).png"))); // NOI18N
        agComponente.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosInterface/add (2).png"))); // NOI18N
        agComponente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agComponenteActionPerformed(evt);
            }
        });
        menuActivo.add(agComponente, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 190, 90));

        jLabel4.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel4.setText("Agregar Componente");
        menuActivo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuActivo, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuActivo, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void codigoActivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoActivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoActivoActionPerformed

    private void agComponenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agComponenteActionPerformed
        listaActivo la = new listaActivo();
        em.getTransaction().begin();
        em.createNativeQuery("INSERT INTO componente (id_activo, nombre, id_componente) VALUES (?, ?, ?)")
                .setParameter(1, id_activo_ingresado)
                .setParameter(2, this.codigoActivo.getText())
                .setParameter(3, null)
                .executeUpdate();
        em.flush();
        datosTransaccion.commit();
        em.close();
        la.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_agComponenteActionPerformed

    private void activoAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activoAtrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_activoAtrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formularioActivoComponente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formularioActivoComponente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formularioActivoComponente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formularioActivoComponente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formularioActivoComponente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton activoAtras;
    private javax.swing.JButton agComponente;
    private javax.swing.JTextField codigoActivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel menuActivo;
    // End of variables declaration//GEN-END:variables
}
