/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.EntityTransaction;
import javax.persistence.Persistence;

/**
 *
 * @author Andrea
 */
public class formularioEmpleado extends javax.swing.JFrame {

    EntityManagerFactory emf = Persistence.createEntityManagerFactory("InventarioPU");
    EntityManager em = emf.createEntityManager();
    EntityTransaction datosTransaccion = em.getTransaction();
    
    /**
     * Creates new form formularioEmpleado
     */
    public formularioEmpleado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        activoAtras = new javax.swing.JButton();
        formularioEmpleado = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nombreFormularioEmpleado = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        fichaFormularioEmpleado = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        empleadoAtras = new javax.swing.JButton();
        agEmpleado = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        activoAtras.setBackground(new java.awt.Color(255, 255, 255));
        activoAtras.setForeground(new java.awt.Color(255, 255, 255));
        activoAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosInterface/back.png"))); // NOI18N
        activoAtras.setBorder(null);
        activoAtras.setBorderPainted(false);
        activoAtras.setContentAreaFilled(false);
        activoAtras.setFocusPainted(false);
        activoAtras.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosInterface/back (2).png"))); // NOI18N
        activoAtras.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosInterface/back (2).png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        formularioEmpleado.setBackground(new java.awt.Color(255, 255, 255));
        formularioEmpleado.setPreferredSize(new java.awt.Dimension(1200, 660));
        formularioEmpleado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Ficha del Empleado");
        formularioEmpleado.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, -1, -1));

        nombreFormularioEmpleado.setBackground(new java.awt.Color(255, 255, 255));
        nombreFormularioEmpleado.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        nombreFormularioEmpleado.setForeground(new java.awt.Color(51, 51, 51));
        nombreFormularioEmpleado.setText("Nombre del Empleado");
        nombreFormularioEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreFormularioEmpleadoActionPerformed(evt);
            }
        });
        formularioEmpleado.add(nombreFormularioEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 190, 40));

        jLabel1.setFont(new java.awt.Font("Bell MT", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Agregar un Empleado");
        formularioEmpleado.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 530, 70));

        fichaFormularioEmpleado.setBackground(new java.awt.Color(255, 255, 255));
        fichaFormularioEmpleado.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        fichaFormularioEmpleado.setForeground(new java.awt.Color(51, 51, 51));
        fichaFormularioEmpleado.setText("Ficha del Empleado");
        formularioEmpleado.add(fichaFormularioEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 190, 40));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Nombre Empleado");
        formularioEmpleado.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 190, 30));

        empleadoAtras.setBackground(new java.awt.Color(255, 255, 255));
        empleadoAtras.setForeground(new java.awt.Color(255, 255, 255));
        empleadoAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosInterface/back.png"))); // NOI18N
        empleadoAtras.setBorder(null);
        empleadoAtras.setBorderPainted(false);
        empleadoAtras.setContentAreaFilled(false);
        empleadoAtras.setFocusPainted(false);
        empleadoAtras.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosInterface/back (2).png"))); // NOI18N
        empleadoAtras.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosInterface/back (2).png"))); // NOI18N
        empleadoAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empleadoAtrasActionPerformed(evt);
            }
        });
        formularioEmpleado.add(empleadoAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 70));

        agEmpleado.setBackground(new java.awt.Color(255, 255, 255));
        agEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        agEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosInterface/add (1).png"))); // NOI18N
        agEmpleado.setBorder(null);
        agEmpleado.setBorderPainted(false);
        agEmpleado.setContentAreaFilled(false);
        agEmpleado.setFocusPainted(false);
        agEmpleado.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosInterface/add (2).png"))); // NOI18N
        agEmpleado.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosInterface/add (2).png"))); // NOI18N
        agEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agEmpleadoActionPerformed(evt);
            }
        });
        formularioEmpleado.add(agEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 230, 120));

        jLabel3.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Agregar Empleado");
        formularioEmpleado.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 460, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(formularioEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(formularioEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreFormularioEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreFormularioEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreFormularioEmpleadoActionPerformed

    private void empleadoAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empleadoAtrasActionPerformed
        listaEmpleado le = new listaEmpleado();
        le.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_empleadoAtrasActionPerformed

    private void agEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agEmpleadoActionPerformed
        this.setVisible(false);
        listaEmpleado le = new listaEmpleado();
        em.getTransaction().begin();
        em.createNativeQuery("INSERT INTO responsableu (id_responsableu, nombre) VALUES (?1, ?2)")
                .setParameter(1, this.fichaFormularioEmpleado.getText())
                .setParameter(2, this.nombreFormularioEmpleado.getText())
                .executeUpdate();
        em.flush();
        datosTransaccion.commit();
        em.close();
        le.setVisible(true);
        
  
    }//GEN-LAST:event_agEmpleadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formularioEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formularioEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formularioEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formularioEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formularioEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton activoAtras;
    private javax.swing.JButton agEmpleado;
    private javax.swing.JButton empleadoAtras;
    private javax.swing.JTextField fichaFormularioEmpleado;
    private javax.swing.JPanel formularioEmpleado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField nombreFormularioEmpleado;
    // End of variables declaration//GEN-END:variables
}
