/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

/**
 *
 * @author Andrea
 */
public class jefe extends javax.swing.JFrame {

    /**
     * Creates new form Jefe
     */
    public jefe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fechaIngresoJefe = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        nombreJefe = new javax.swing.JTextField();
        jefeAtras = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosInterface/defb4161eb05111ed5813229b9611c95.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosInterface/man (1).png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 130, 137));

        jLabel3.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Fecha de Ingreso");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 330, 40));

        fechaIngresoJefe.setBackground(new java.awt.Color(255, 255, 255));
        fechaIngresoJefe.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        fechaIngresoJefe.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fechaIngresoJefe.setText("Fecha de Ingreso");
        fechaIngresoJefe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(123, 211, 240)));
        fechaIngresoJefe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaIngresoJefeActionPerformed(evt);
            }
        });
        jPanel2.add(fechaIngresoJefe, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 310, 40));

        jLabel5.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Nombre del Jefe de la Unidad Operativa");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 330, 40));

        nombreJefe.setBackground(new java.awt.Color(255, 255, 255));
        nombreJefe.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        nombreJefe.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nombreJefe.setText("Nombre de Jefe");
        nombreJefe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(123, 211, 240)));
        nombreJefe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreJefeActionPerformed(evt);
            }
        });
        jPanel2.add(nombreJefe, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 310, 40));

        jefeAtras.setBackground(new java.awt.Color(255, 255, 255));
        jefeAtras.setForeground(new java.awt.Color(255, 255, 255));
        jefeAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosInterface/back.png"))); // NOI18N
        jefeAtras.setBorder(null);
        jefeAtras.setBorderPainted(false);
        jefeAtras.setContentAreaFilled(false);
        jefeAtras.setFocusPainted(false);
        jefeAtras.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosInterface/back (2).png"))); // NOI18N
        jefeAtras.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosInterface/back (2).png"))); // NOI18N
        jefeAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jefeAtrasActionPerformed(evt);
            }
        });
        jPanel2.add(jefeAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 80, 70));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 410, 480));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosInterface/defb4161eb05111ed5813229b9611c95.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jefeAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jefeAtrasActionPerformed
        principalEmpleado pe = new principalEmpleado();
        pe.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jefeAtrasActionPerformed

    private void nombreJefeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreJefeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreJefeActionPerformed

    private void fechaIngresoJefeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaIngresoJefeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaIngresoJefeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jefe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jefe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jefe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jefe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jefe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fechaIngresoJefe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jefeAtras;
    private javax.swing.JTextField nombreJefe;
    // End of variables declaration//GEN-END:variables
}
