/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import static Interface.principalEmpleado.a;
import static Interface.principalJefe.b;

/**
 *
 * @author Andrea
 */
public class listaUnidadOperativa extends javax.swing.JFrame {

    /**
     * Creates new form UnidadOperativa
     */
    public listaUnidadOperativa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        unidadoperativa = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaUnidadOperativa = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        agUnidadOperativa = new javax.swing.JButton();
        unidadOperativaAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        unidadoperativa.setBackground(new java.awt.Color(255, 255, 255));
        unidadoperativa.setPreferredSize(new java.awt.Dimension(1200, 700));
        unidadoperativa.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(188, 212, 230));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        unidadoperativa.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1200, 10));

        listaUnidadOperativa.setBackground(new java.awt.Color(255, 255, 255));
        listaUnidadOperativa.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        listaUnidadOperativa.setForeground(new java.awt.Color(255, 255, 255));
        listaUnidadOperativa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre"
            }
        ));
        jScrollPane1.setViewportView(listaUnidadOperativa);

        unidadoperativa.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 1130, 500));

        jLabel1.setFont(new java.awt.Font("Bell MT", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Lista Unidad Operativa ");
        unidadoperativa.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 1000, 70));

        agUnidadOperativa.setBackground(new java.awt.Color(255, 255, 255));
        agUnidadOperativa.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        agUnidadOperativa.setForeground(new java.awt.Color(0, 0, 0));
        agUnidadOperativa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosInterface/add.png"))); // NOI18N
        agUnidadOperativa.setText("Agregar Unidad Operativa");
        agUnidadOperativa.setBorder(null);
        agUnidadOperativa.setBorderPainted(false);
        agUnidadOperativa.setContentAreaFilled(false);
        agUnidadOperativa.setFocusPainted(false);
        agUnidadOperativa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agUnidadOperativaActionPerformed(evt);
            }
        });
        unidadoperativa.add(agUnidadOperativa, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 350, 70));

        unidadOperativaAtras.setBackground(new java.awt.Color(255, 255, 255));
        unidadOperativaAtras.setForeground(new java.awt.Color(255, 255, 255));
        unidadOperativaAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosInterface/back.png"))); // NOI18N
        unidadOperativaAtras.setBorder(null);
        unidadOperativaAtras.setBorderPainted(false);
        unidadOperativaAtras.setContentAreaFilled(false);
        unidadOperativaAtras.setFocusPainted(false);
        unidadOperativaAtras.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosInterface/back (2).png"))); // NOI18N
        unidadOperativaAtras.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosInterface/back (2).png"))); // NOI18N
        unidadOperativaAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unidadOperativaAtrasActionPerformed(evt);
            }
        });
        unidadoperativa.add(unidadOperativaAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(unidadoperativa, javax.swing.GroupLayout.PREFERRED_SIZE, 1170, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(unidadoperativa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agUnidadOperativaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agUnidadOperativaActionPerformed
        formularioUnidad fuo = new formularioUnidad();
        fuo.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_agUnidadOperativaActionPerformed

    private void unidadOperativaAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unidadOperativaAtrasActionPerformed
        
        if (a == 1){
                a--;
                principalEmpleado pe = new principalEmpleado();
                pe.setVisible(true);
                this.setVisible(false);
                        }else if(b == 1){
                                b--;
                                principalJefe pj = new principalJefe();
                                pj.setVisible(true);
                                this.setVisible(false);
                                }

    }//GEN-LAST:event_unidadOperativaAtrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(listaUnidadOperativa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(listaUnidadOperativa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(listaUnidadOperativa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(listaUnidadOperativa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new listaUnidadOperativa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agUnidadOperativa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable listaUnidadOperativa;
    private javax.swing.JButton unidadOperativaAtras;
    private javax.swing.JPanel unidadoperativa;
    // End of variables declaration//GEN-END:variables
}
