/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import static Interface.principalEmpleado.a;
import static Interface.principalJefe.b;

/**
 *
 * @author Andrea
 */
public class listaEmpleado extends javax.swing.JFrame {

    /**
     * Creates new form Empleado
     */
    public listaEmpleado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        empleado = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaEmpleado = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        agEmpleado = new javax.swing.JButton();
        empleadoAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        empleado.setBackground(new java.awt.Color(255, 255, 255));
        empleado.setPreferredSize(new java.awt.Dimension(1200, 700));
        empleado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(188, 212, 230));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        empleado.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1200, 10));

        listaEmpleado.setBackground(new java.awt.Color(255, 255, 255));
        listaEmpleado.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        listaEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        listaEmpleado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ficha", "Nombre", "Unidad Operativa"
            }
        ));
        jScrollPane1.setViewportView(listaEmpleado);

        empleado.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 1150, 470));

        jLabel1.setFont(new java.awt.Font("Bell MT", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Lista de Empleados ");
        empleado.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 1050, 70));

        agEmpleado.setBackground(new java.awt.Color(255, 255, 255));
        agEmpleado.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        agEmpleado.setForeground(new java.awt.Color(0, 0, 0));
        agEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosInterface/add.png"))); // NOI18N
        agEmpleado.setText(" Agregar Empleado");
        agEmpleado.setBorder(null);
        agEmpleado.setBorderPainted(false);
        agEmpleado.setContentAreaFilled(false);
        agEmpleado.setFocusPainted(false);
        agEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agEmpleadoActionPerformed(evt);
            }
        });
        empleado.add(agEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 230, 70));

        empleadoAtras.setBackground(new java.awt.Color(255, 255, 255));
        empleadoAtras.setForeground(new java.awt.Color(255, 255, 255));
        empleadoAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosInterface/back.png"))); // NOI18N
        empleadoAtras.setBorder(null);
        empleadoAtras.setBorderPainted(false);
        empleadoAtras.setContentAreaFilled(false);
        empleadoAtras.setFocusPainted(false);
        empleadoAtras.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosInterface/back (2).png"))); // NOI18N
        empleadoAtras.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosInterface/back (2).png"))); // NOI18N
        empleadoAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empleadoAtrasActionPerformed(evt);
            }
        });
        empleado.add(empleadoAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 1170, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agEmpleadoActionPerformed
        formularioEmpleado fe = new formularioEmpleado();
        fe.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_agEmpleadoActionPerformed

    private void empleadoAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empleadoAtrasActionPerformed
          if (a == 1){
            a--;
            principalEmpleado pe = new principalEmpleado();
            pe.setVisible(true);
            this.setVisible(false);
        }else if(b == 1){
                b--;
                principalJefe pj = new principalJefe();
                pj.setVisible(true);
                this.setVisible(false);
                }
    }//GEN-LAST:event_empleadoAtrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(listaEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(listaEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(listaEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(listaEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new listaEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agEmpleado;
    private javax.swing.JPanel empleado;
    private javax.swing.JButton empleadoAtras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable listaEmpleado;
    // End of variables declaration//GEN-END:variables
}
