/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import inventario.Sede;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.EntityTransaction;
import javax.persistence.Persistence;
import javax.persistence.TypedQuery;


/**
 *
 * @author Andrea
 */
public class login extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form login
     */
    
    EntityManagerFactory emf = Persistence.createEntityManagerFactory("InventarioPU");
    EntityManager em = emf.createEntityManager();
    EntityTransaction datosTransaccion = em.getTransaction();
    
    public static String mi_sede = "";
    
    
    
    public login() {
        initComponents();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Ingresar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fichaEmpleado = new javax.swing.JTextField();
        jefeOperativo = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Ingresar.setBackground(new java.awt.Color(255, 255, 255));
        Ingresar.setForeground(new java.awt.Color(255, 255, 255));
        Ingresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosInterface/login (2).png"))); // NOI18N
        Ingresar.setBorder(null);
        Ingresar.setBorderPainted(false);
        Ingresar.setContentAreaFilled(false);
        Ingresar.setFocusPainted(false);
        Ingresar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosInterface/login.png"))); // NOI18N
        Ingresar.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosInterface/login.png"))); // NOI18N
        Ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarActionPerformed(evt);
            }
        });
        jPanel1.add(Ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosInterface/man (1).png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 130, 137));

        jLabel3.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Ingrese su ficha ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 250, 40));

        fichaEmpleado.setBackground(new java.awt.Color(255, 255, 255));
        fichaEmpleado.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        fichaEmpleado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fichaEmpleado.setText("Ficha");
        fichaEmpleado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(123, 211, 240)));
        fichaEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fichaEmpleadoActionPerformed(evt);
            }
        });
        jPanel1.add(fichaEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 170, 40));

        jefeOperativo.setBackground(new java.awt.Color(255, 255, 255));
        jefeOperativo.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        jefeOperativo.setForeground(new java.awt.Color(0, 0, 0));
        jefeOperativo.setText("Jefe de Unidad Operativa");
        jefeOperativo.setActionCommand("jefeUnidad");
        jefeOperativo.setBorder(null);
        jefeOperativo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jefeOperativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jefeOperativoActionPerformed(evt);
            }
        });
        jPanel1.add(jefeOperativo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 190, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 430, 450));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosInterface/defb4161eb05111ed5813229b9611c95.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fichaEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fichaEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fichaEmpleadoActionPerformed

    private void IngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarActionPerformed
        if(jefeOperativo.isSelected()){
            
            principalJefe nj = new principalJefe();
            nj.setVisible(true);
            this.setVisible(false);
        }else{
            principalEmpleado pe = new principalEmpleado();
            em.getTransaction().begin();
            TypedQuery<Sede> r_sede = em.createNamedQuery("Sede.ingresar", Sede.class)
                    .setParameter(1, this.fichaEmpleado.getText());
            List<Sede> l_sede = r_sede.getResultList();
            Sede sede = l_sede.get(0);
            mi_sede = sede.getIdSede();
            em.flush();
            datosTransaccion.commit();
            em.close();
            pe.setVisible(true);
            this.setVisible(false);
        
        }
    }//GEN-LAST:event_IngresarActionPerformed

    private void jefeOperativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jefeOperativoActionPerformed
        
    }//GEN-LAST:event_jefeOperativoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ingresar;
    private javax.swing.JTextField fichaEmpleado;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox jefeOperativo;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        
    }
}
