/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

/**
 *
 * @author Andrea
 */
public class principalJefe extends javax.swing.JFrame {

    public static int b = 0;
    public principalJefe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuJefe = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nombreJefe = new javax.swing.JLabel();
        UnidadOperativaJefe1 = new javax.swing.JLabel();
        SedeJefe = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        botonActivoJefe = new javax.swing.JButton();
        botonEmpleadoJefe = new javax.swing.JButton();
        botonEstadisticaJefe = new javax.swing.JButton();
        BotonInventarioJefe = new javax.swing.JButton();
        BotonMovilizacionJefe = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        principalJefeAtras = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        botonUnidadOperativa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 700));

        menuJefe.setBackground(new java.awt.Color(255, 255, 255));
        menuJefe.setPreferredSize(new java.awt.Dimension(1200, 700));
        menuJefe.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosInterface/man (1).png"))); // NOI18N
        menuJefe.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 150, 160));

        nombreJefe.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        nombreJefe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombreJefe.setText("Nombre Jefe");
        menuJefe.add(nombreJefe, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 500, 40));

        UnidadOperativaJefe1.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        UnidadOperativaJefe1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UnidadOperativaJefe1.setText("Unidad operativa jefe");
        UnidadOperativaJefe1.setToolTipText("");
        UnidadOperativaJefe1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menuJefe.add(UnidadOperativaJefe1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 50, 270, 20));

        SedeJefe.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        SedeJefe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SedeJefe.setText("Sede jefe");
        SedeJefe.setToolTipText("");
        SedeJefe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menuJefe.add(SedeJefe, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 100, 270, 20));

        jPanel1.setBackground(new java.awt.Color(188, 212, 230));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        menuJefe.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 1200, 10));

        botonActivoJefe.setBackground(new java.awt.Color(255, 255, 255));
        botonActivoJefe.setForeground(new java.awt.Color(255, 255, 255));
        botonActivoJefe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosInterface/furniture-and-household (1).png"))); // NOI18N
        botonActivoJefe.setBorder(null);
        botonActivoJefe.setBorderPainted(false);
        botonActivoJefe.setContentAreaFilled(false);
        botonActivoJefe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonActivoJefe.setFocusPainted(false);
        botonActivoJefe.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosInterface/furniture-and-household (3).png"))); // NOI18N
        botonActivoJefe.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosInterface/furniture-and-household (3).png"))); // NOI18N
        botonActivoJefe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActivoJefeActionPerformed(evt);
            }
        });
        menuJefe.add(botonActivoJefe, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 230, 170));

        botonEmpleadoJefe.setBackground(new java.awt.Color(255, 255, 255));
        botonEmpleadoJefe.setForeground(new java.awt.Color(255, 255, 255));
        botonEmpleadoJefe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosInterface/man (4).png"))); // NOI18N
        botonEmpleadoJefe.setBorder(null);
        botonEmpleadoJefe.setBorderPainted(false);
        botonEmpleadoJefe.setContentAreaFilled(false);
        botonEmpleadoJefe.setFocusPainted(false);
        botonEmpleadoJefe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonEmpleadoJefe.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosInterface/man (3).png"))); // NOI18N
        botonEmpleadoJefe.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosInterface/man (3).png"))); // NOI18N
        botonEmpleadoJefe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEmpleadoJefeActionPerformed(evt);
            }
        });
        menuJefe.add(botonEmpleadoJefe, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, 260, 180));

        botonEstadisticaJefe.setBackground(new java.awt.Color(255, 255, 255));
        botonEstadisticaJefe.setForeground(new java.awt.Color(255, 255, 255));
        botonEstadisticaJefe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosInterface/progress.png"))); // NOI18N
        botonEstadisticaJefe.setBorder(null);
        botonEstadisticaJefe.setBorderPainted(false);
        botonEstadisticaJefe.setContentAreaFilled(false);
        botonEstadisticaJefe.setFocusPainted(false);
        botonEstadisticaJefe.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosInterface/progress (1).png"))); // NOI18N
        botonEstadisticaJefe.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosInterface/progress (1).png"))); // NOI18N
        botonEstadisticaJefe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEstadisticaJefeActionPerformed(evt);
            }
        });
        menuJefe.add(botonEstadisticaJefe, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 170, 250, 180));

        BotonInventarioJefe.setBackground(new java.awt.Color(255, 255, 255));
        BotonInventarioJefe.setForeground(new java.awt.Color(255, 255, 255));
        BotonInventarioJefe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosInterface/treasure.png"))); // NOI18N
        BotonInventarioJefe.setBorder(null);
        BotonInventarioJefe.setBorderPainted(false);
        BotonInventarioJefe.setContentAreaFilled(false);
        BotonInventarioJefe.setFocusPainted(false);
        BotonInventarioJefe.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosInterface/treasure (1).png"))); // NOI18N
        BotonInventarioJefe.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosInterface/treasure (1).png"))); // NOI18N
        BotonInventarioJefe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonInventarioJefeActionPerformed(evt);
            }
        });
        menuJefe.add(BotonInventarioJefe, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, 220, 160));

        BotonMovilizacionJefe.setBackground(new java.awt.Color(255, 255, 255));
        BotonMovilizacionJefe.setForeground(new java.awt.Color(255, 255, 255));
        BotonMovilizacionJefe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosInterface/moving.png"))); // NOI18N
        BotonMovilizacionJefe.setBorder(null);
        BotonMovilizacionJefe.setBorderPainted(false);
        BotonMovilizacionJefe.setContentAreaFilled(false);
        BotonMovilizacionJefe.setFocusPainted(false);
        BotonMovilizacionJefe.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosInterface/moving (1).png"))); // NOI18N
        BotonMovilizacionJefe.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosInterface/moving (1).png"))); // NOI18N
        BotonMovilizacionJefe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMovilizacionJefeActionPerformed(evt);
            }
        });
        menuJefe.add(BotonMovilizacionJefe, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 430, 230, 160));

        jLabel1.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Unidades Operativas");
        menuJefe.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 600, 180, 70));

        jLabel3.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Activos");
        menuJefe.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 180, 70));

        jLabel4.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Empleados");
        menuJefe.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 350, 180, 70));

        jLabel5.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Estadisticas");
        menuJefe.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 340, 180, 70));

        jLabel6.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Inventario");
        menuJefe.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 600, 210, 70));

        principalJefeAtras.setBackground(new java.awt.Color(255, 255, 255));
        principalJefeAtras.setForeground(new java.awt.Color(255, 255, 255));
        principalJefeAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosInterface/back.png"))); // NOI18N
        principalJefeAtras.setBorder(null);
        principalJefeAtras.setBorderPainted(false);
        principalJefeAtras.setContentAreaFilled(false);
        principalJefeAtras.setFocusPainted(false);
        principalJefeAtras.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosInterface/back (2).png"))); // NOI18N
        principalJefeAtras.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosInterface/back (2).png"))); // NOI18N
        principalJefeAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                principalJefeAtrasActionPerformed(evt);
            }
        });
        menuJefe.add(principalJefeAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 80, 70));

        jLabel7.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Movilizaciones");
        menuJefe.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 600, 180, 70));

        botonUnidadOperativa.setBackground(new java.awt.Color(255, 255, 255));
        botonUnidadOperativa.setForeground(new java.awt.Color(255, 255, 255));
        botonUnidadOperativa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosInterface/architecture-and-city.png"))); // NOI18N
        botonUnidadOperativa.setBorder(null);
        botonUnidadOperativa.setBorderPainted(false);
        botonUnidadOperativa.setContentAreaFilled(false);
        botonUnidadOperativa.setFocusPainted(false);
        botonUnidadOperativa.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosInterface/architecture-and-city (1).png"))); // NOI18N
        botonUnidadOperativa.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosInterface/architecture-and-city (1).png"))); // NOI18N
        botonUnidadOperativa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonUnidadOperativaActionPerformed(evt);
            }
        });
        menuJefe.add(botonUnidadOperativa, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 430, 230, 160));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuJefe, javax.swing.GroupLayout.PREFERRED_SIZE, 1170, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuJefe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonEmpleadoJefeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEmpleadoJefeActionPerformed
        listaEmpleado le = new listaEmpleado();
        le.setVisible(true);
        this.setVisible(false);
        b++;
    }//GEN-LAST:event_botonEmpleadoJefeActionPerformed

    private void botonActivoJefeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActivoJefeActionPerformed
        listaActivo la = new listaActivo();
        la.setVisible(true);
        this.setVisible(false);
        b++;
    }//GEN-LAST:event_botonActivoJefeActionPerformed

    private void botonEstadisticaJefeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEstadisticaJefeActionPerformed
        estadistica e = new estadistica();
        e.setVisible(true);
        this.setVisible(false);
        b++;
    }//GEN-LAST:event_botonEstadisticaJefeActionPerformed

    private void BotonInventarioJefeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonInventarioJefeActionPerformed
        inventario i = new inventario();
        i.setVisible(true);
        this.setVisible(false);
        b++;
                              
    }//GEN-LAST:event_BotonInventarioJefeActionPerformed

    private void BotonMovilizacionJefeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMovilizacionJefeActionPerformed
        listaMovilizacion lm = new listaMovilizacion();
        lm.setVisible(true);
        this.setVisible(false);
        b++;
    }//GEN-LAST:event_BotonMovilizacionJefeActionPerformed

    private void principalJefeAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_principalJefeAtrasActionPerformed
        login log = new login();
        log.setVisible(true);
        this.setVisible(false);
        
        
    }//GEN-LAST:event_principalJefeAtrasActionPerformed

    private void botonUnidadOperativaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonUnidadOperativaActionPerformed
        listaUnidadOperativa luo = new listaUnidadOperativa();
        luo.setVisible(true);
        this.setVisible(false);
        b++;
    }//GEN-LAST:event_botonUnidadOperativaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principalJefe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principalJefe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principalJefe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principalJefe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principalJefe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonInventarioJefe;
    private javax.swing.JButton BotonMovilizacionJefe;
    private javax.swing.JLabel SedeJefe;
    private javax.swing.JLabel UnidadOperativaJefe1;
    private javax.swing.JButton botonActivoJefe;
    private javax.swing.JButton botonEmpleadoJefe;
    private javax.swing.JButton botonEstadisticaJefe;
    private javax.swing.JButton botonUnidadOperativa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel menuJefe;
    private javax.swing.JLabel nombreJefe;
    private javax.swing.JButton principalJefeAtras;
    // End of variables declaration//GEN-END:variables
}
